# dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.callingninja.tmpl /etc/nginx/conf.d/default.conf
# dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.cloud.tmpl /etc/nginx/conf.d/default.conf
dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.callingninja.xyz.tmpl /etc/nginx/conf.d/default.conf
nginx: nginx
